[package]
name = "workmate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.7", features = ["derive"] }
mouse-rs = "0.4.1"
log = "0.4.0"
